name = "Objects"
uuid = "62ecdadc-e19b-4eca-b0de-2efed354d683"
authors = ["Rellikeht <michaelhemperek@gmail.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Vectors = "3cde98ac-47c7-4389-9f21-dc41dd2cbfe5"
