# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.3"
manifest_format = "2.0"
project_hash = "02aa763e5ca695ffdcc7f67b0c0b3c361225b62b"

[[deps.Objects]]
deps = ["Vectors"]
path = "../Objects"
uuid = "62ecdadc-e19b-4eca-b0de-2efed354d683"
version = "0.1.0"

[[deps.Vectors]]
path = "../Vectors"
uuid = "3cde98ac-47c7-4389-9f21-dc41dd2cbfe5"
version = "0.1.0"
